
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package se_examples.wssecurity_x509;

import java.util.logging.Logger;

import org.example.myservice.MyService;
import org.jboss.ws.api.annotation.EndpointConfig;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-23T10:27:36.768-05:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "myService",
                      portName = "myServiceSOAP",
                      targetNamespace = "http://www.example.org/myService/",
                      wsdlLocation = "file:/home/pazfernando/jbdevstudio_wssecurity_workspace/wssecurity-x509/src/main/resources/myService.wsdl",
                      endpointInterface = "org.example.myservice.MyService")
@EndpointConfig(configFile = "WEB-INF/jaxws-endpoint-config.xml", configName = "Custom WS-Security Endpoint")
public class MyServiceImpl implements MyService {

    private static final Logger LOG = Logger.getLogger(MyServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.myservice.MyService#newOperation(java.lang.String  in )*
     */
    public java.lang.String newOperation(java.lang.String in) { 
        LOG.info("Executing operation newOperation");
        System.out.println(in);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
